before_install:
  - gem update bundler
  - bundle --version
  - gem update --system 2.1.11
  - gem --version
rvm:
  - 2.3
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - rbx-2
  - ree
